PartyPalace/force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PartyPalace/force-app/main/default/classes/RecommendationsControllerTest.cls
////////////////////////////////////////
//
//	Name: RecommendationsControllerTest
//	Author: Abdul-Shahid Wali
//	Created: 5/04/21
//	Updated: 5/04/21
//	Description: Test class for the RecommendationsController class
//	
////////////////////////////////////////
@isTest
public class RecommendationsControllerTest {
    //Tests the two methods of the RecommendationController class
    @isTest public static void test(){
    RecommendationsController recCon = new RecommendationsController();
    Transaction__c trans = new Transaction__c(Status__c = 'Active');
    Store_Product__c product = new Store_Product__c(Name = 'Balloons');
    recCon.clickedItem = 'Balloons';
    insert trans;
    insert product;
    recCon.GetRecommendations();
    recCon.AddToCart();
    }

}