PartyPalace/force-app/main/default/objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Salesperson Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesperson__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Salespeople</relationshipLabel>
    <relationshipName>Salespeople</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Location__c/Store_Location__c.object-meta.xml
<CustomObject>
    <label>Store Location</label>
    <nameField>
        <label>Store Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Rental_Cost__c +  Products_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PartyPalace/force-app/main/default/classes/CurrentTransaction.cls
public class CurrentTransaction {
    public Transaction__c Trans{get;set;}
    Id currentUser = UserInfo.getUserId();
    public CurrentTransaction(){
        User you = [SELECT Name, ContactID FROM User where id =: currentUser];
        trans = [SELECT Name, Contact__c, Status__c, Store_Location__c, Total_Cost__c, Salesperson__c FROM Transaction__c WHERE Status__c =: 'Active' AND Contact__c =: you.ContactId];
    }
    public void setCurrentTransaction(Transaction__c newTransaction){
        trans = newTransaction;
    }
}