PartyPalace/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Store_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ballons</fullName>
                <default>true</default>
                <label>Ballons</label>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Confetti</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PartyPalace/force-app/main/default/classes/RecommendationsController.cls
////////////////////////////////////////
//
//	Name: RecommendationsController
//	Author: Abdul-Shahid Wali
//	Created: 4/30/21
//	Updated: 5/04/21
//	Description: Custom Controller for the RecommendationsView visualforce page
//	
////////////////////////////////////////


public class RecommendationsController {
    
    public string category {get;set;}
    public string clickedItem {get;set;}
    public List<Store_Product__c> productsToRecommend {get;set;}
    
 	//Filters store products by category
    public void GetRecommendations(){
        String s = 'SELECT Name, Category__c FROM Store_Product__c WHERE Category__c =: category';
        productsToRecommend = database.query(s);

    }
    //Adds an store product to the customer's cart. Currently non-functional
    public void AddToCart(){
        String userID = userInfo.getUserId();
        User currentUser = [SELECT ContactID FROM User WHERE Id =: userID];
        //Get an active transaction
        Transaction__c  trans = [SELECT Id FROM Transaction__c WHERE Status__c = 'Active'];
        //Get the product the customer clicked on
        Store_Product__c product = [SELECT Id FROM Store_Product__c WHERE Name =: clickedItem];
        //Create a new product line for the current product and transaction
        Product_Line__c productLine = new Product_Line__c(Product__c = product.Id, Transaction__c = trans.id, Quantity__c = 1);
    }

}