PartyPalace/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/StoreProductsControllerTest.cls
@isTest
public class StoreProductsControllerTest {

    @isTest(SeeAllData=True)
    private static void renderPage(){
        Contact c = [SELECT Name,id FROM Contact WHERE firstName='David'];
        User u = [SELECT Name,id FROM User WHERE ContactId=:c.id];
        //PageReference PageRef = Page.StoreProductsView;
        //Test.setCurrentPage(PageRef);
        
        List<Store_Product__c> products = [SELECT Name FROM Store_Product__c LIMIT 15];
        System.RunAs(u){
            // initialized page correctly test
            StoreProductsController controller = new StoreProductsController();
            List<StoreProductsController.ProductsWrapper> wrapperList = controller.GetProductWrapper();
            system.assertEquals((products.size()/3), wrapperList.size());
            
            // next page test
            controller.next();
            products = [SELECT Name FROM Store_Product__c LIMIT 15 OFFSET 15];
         	wrapperList = controller.GetProductWrapper();
            system.assertEquals((products.size()/3)+1, wrapperList.size());
            
            // attempt to go to next page from last page
            controller.next();
            products = [SELECT Name FROM Store_Product__c LIMIT 15 OFFSET 15];
            wrapperList = controller.GetProductWrapper();
            system.assertEquals((products.size()/3)+1, wrapperList.size());
            
            // previous page test
            controller.prev();
            products = [SELECT Name FROM Store_Product__c LIMIT 15];
         	wrapperList = controller.GetProductWrapper();
            system.assertEquals((products.size()/3), wrapperList.size());
            
            // attempt to go to previous page from first page
            controller.prev();
            products = [SELECT Name FROM Store_Product__c LIMIT 15];
         	wrapperList = controller.GetProductWrapper();
            system.assertEquals((products.size()/3), wrapperList.size());
        }
    }
    
    @isTest
    private static void addToCart(){
        Contact c = [SELECT Name,id FROM Contact WHERE firstName='David'];
        User u = [SELECT Name,id FROM User WHERE ContactId=:c.id];
        Transaction__c userTrans = new Transaction__c(Status__c='Active');
        
        Store_Product__c product = new Store_Product__c(Name='test item');
        insert product;
        System.RunAs(u){
            StoreProductsController controller = new StoreProductsController();
            List<StoreProductsController.ProductsWrapper> wrapperList = controller.GetProductWrapper();
            controller.clickedItem = product.Name;
            controller.AddToCart();
            
            Product_Line__c lineItem = [SELECT Product__c,Transaction__c FROM Product_Line__c WHERE Transaction__c=:userTrans.id];
            Store_Product__c item = [SELECT Name FROM Store_Product__c WHERE Id=:lineItem.Product__c];
            system.assertEquals(product.Name, item.Name);
        }
    }
       
}