PartyPalace/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Salesperson Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesperson__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Salespeople</relationshipLabel>
    <relationshipName>Salespeople</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Store_Inventory__c/Store_Inventory__c.object-meta.xml
<CustomObject>
    <label>Store Inventory</label>
    <nameField>
        <displayFormat>SINV -{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Inventory__c/fields/Number_in_Stock__c.field-meta.xml
<CustomField>
    <fullName>Number_in_Stock__c</fullName>
    <label>Number in Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Inventory__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Store Inventories</relationshipLabel>
    <relationshipName>Store_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Inventory__c/fields/Store_Product__c.field-meta.xml
<CustomField>
    <fullName>Store_Product__c</fullName>
    <label>Store Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipLabel>Store Inventories</relationshipLabel>
    <relationshipName>Store_Inventories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Location__c/Store_Location__c.object-meta.xml
<CustomObject>
    <label>Store Location</label>
    <nameField>
        <label>Store Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/classes/StoreProductLineTest.cls
///////////////////////////////////////////////////////////////////////////
//
// Name: StoreProductLineTest
// Author: Andrew Sutton
// Created 4/10/2021
// Updated 4/14/2021
//
//
/////////////////////////////////////////////////////////////////////////////


@istest
private class StoreProductLineTest {
	@isTest static void singleTest(){
        Store_Location__c loc = new Store_Location__c(name = 'NY');
        insert loc;
        Store_Product__c prod = new Store_Product__c(name = 'Hat', Price_Per_Unit__c = 3);
        insert prod;
        Salesperson__c chad = new Salesperson__c(Store_Location__c = loc.id);
        insert chad;
        Store_Inventory__c inv = new Store_Inventory__c(Store_Location__c = loc.id, Store_Product__c = prod.id, Number_in_Stock__c = 100);
        insert inv;
        Transaction__c trans = new Transaction__c(Store_Location__c = loc.id, Salesperson__c = chad.id);
        insert trans;
        Product_Line__c line = new Product_Line__c(Transaction__c = trans.id, Product__c = prod.id, Quantity__c = 10);
       	insert line;
       	Product_Line__c line2 = new Product_Line__c(Transaction__c = trans.id, Product__c = prod.id, Quantity__c = 101);
        line.Quantity__c = 101;
        Integer numFailed = 0;
        Database.SaveResult sr = Database.insert(line2, false);
        if(!sr.isSuccess()){
            numFailed = 1;
        }
        Database.SaveResult sr2 = Database.update(line, false);
        if(!sr.isSuccess()){
            numFailed = 2;
        }
        System.assertEquals(2, numFailed);
        delete line;
    }
    
    
    
}