PartyPalace/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Inventory__c/Store_Inventory__c.object-meta.xml
<CustomObject>
    <label>Store Inventory</label>
    <nameField>
        <displayFormat>SINV -{0000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Inventory__c/fields/Number_in_Stock__c.field-meta.xml
<CustomField>
    <fullName>Number_in_Stock__c</fullName>
    <label>Number in Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Inventory__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Store Inventories</relationshipLabel>
    <relationshipName>Store_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Inventory__c/fields/Store_Product__c.field-meta.xml
<CustomField>
    <fullName>Store_Product__c</fullName>
    <label>Store Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipLabel>Store Inventories</relationshipLabel>
    <relationshipName>Store_Inventories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Location__c/Store_Location__c.object-meta.xml
<CustomObject>
    <label>Store Location</label>
    <nameField>
        <label>Store Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Rental_Cost__c +  Products_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PartyPalace/force-app/main/default/classes/StoreProductLineTriggerHandler.cls
///////////////////////////////////////////////////////////////////////////
//
// Name: StoreProductLineTriggerHandler
// Author: Andrew Sutton
// Created 4/10/2021
// Updated 4/14/2021
//
//
/////////////////////////////////////////////////////////////////////////////
public class StoreProductLineTriggerHandler {
    public static void insertProducts(List<Product_Line__c> newProducts) {
        updateInventory(newProducts);
        updateTotalCost(newProducts);
        
    }
    public static void updateInventory(List<Product_Line__c> newProducts){   
        List<Store_Inventory__c> inventories = findInventory(newProducts);    
        For(Product_Line__c pl: newProducts){
            For(Store_Inventory__c inventory:inventories){
            //subtract From Inventory
            inventory.Number_in_Stock__c = inventory.Number_in_Stock__c - pl.Quantity__c;
            //Ask if we are out of stock
            if (inventory.Number_in_Stock__c < 0){
                pl.Quantity__c.addError('Not enough in Stock');
            }
        }
        }
        update inventories;
        
    }
    public static void updateTotalCost(List<Product_Line__c> newProductLines)
    {
        List<Store_Product__c> Products = [SELECT Price_Per_Unit__c FROM Store_Product__c];
        for (Product_Line__c pl: newProductLines){
            for(Store_Product__c p: products){
                if(pl.Product__c == p.id){
                    pl.Total_Cost__c = p.Price_Per_Unit__c * pl.Quantity__c;
                }
                
            }
        }
    }
    public static void editProducts(List<Product_Line__c> newProducts, List<Product_Line__c> oldProducts){
        List<Store_Inventory__c> oldInvs = findInventory(oldProducts);
        List<Store_Inventory__c> newInvs = findInventory(newProducts);
        //get the difference in inventory from old to new
        //for(Integer i = 0; i < newProducts.size(); i++){
        //newInvs[i].Number_in_Stock__c = newInvs[i].Number_in_Stock__c - (newProducts[i].Quantity__c - oldProducts[i].Quantity__c);
        //Ask if we are out of stock
        //if (newInvs[i].Number_in_Stock__c < 0){
        //    newProducts[i].Quantity__c.addError('Not enough in Stock');
        //}
        //}
        update newInvs;
        updateTotalCost(newProducts);
        
        
    }
    
    public static void deleteLineItem(List<Product_Line__c> newProducts){
        List<Store_Inventory__c> inventory = findInventory(newProducts);
        For(Product_Line__c pl: newProducts){
            //add the quantity back to the inventory
            //inventory.Number_in_Stock__c = inventory.Number_in_Stock__c + pl.Quantity__c;   
        }
        update inventory;
    }
    static List<Store_Inventory__c> findInventory(List<Product_Line__c> newProducts)
    {
        Set<id> transid = new set<id>();
        for(Product_Line__c pl :newProducts){
            transid.add(pl.Transaction__c);
        }
        Set<id> productId = new set<id>();
        for(Product_Line__c pl : newProducts){
            productID.add(pl.product__c);
        }
        //Grab the transactions that matches our Product Line item's transactions
        List<Transaction__c> trans = [SELECT Store_Location__c FROM Transaction__c WHERE id = : TransID];
        set<id> locationID = new set<id>();
        for(Transaction__c tran : trans){
            locationID.add(tran.Store_Location__c);
        }
        List<Store_Inventory__c> inventory = [SELECT Number_in_Stock__c, Store_Product__c FROM Store_Inventory__c WHERE Store_Product__c IN :productID AND Store_Location__c =: locationID];
        return inventory;
    }    

}