PartyPalace/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Salesperson__c/Salesperson__c.object-meta.xml
<CustomObject>
    <label>Salesperson</label>
    <nameField>
        <label>Salesperson Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salespeople</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Salesperson__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Salespeople</relationshipLabel>
    <relationshipName>Salespeople</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Location__c/Store_Location__c.object-meta.xml
<CustomObject>
    <label>Store Location</label>
    <nameField>
        <label>Store Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Locations</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Transaction__c/fields/Salesperson__c.field-meta.xml
<CustomField>
    <fullName>Salesperson__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Salesperson</label>
    <referenceTo>Salesperson__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Store_Location__c.field-meta.xml
<CustomField>
    <fullName>Store_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Store Location</label>
    <referenceTo>Store_Location__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Rental_Cost__c +  Products_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PartyPalace/force-app/main/default/classes/TransactionPageController.cls
///////////////////////////////////////////////////////////////////////////
//
// Name: TransactionPageController
// Author: Andrew Sutton
// Created 5/4/2021
// Updated 5/4/2021
//
//
/////////////////////////////////////////////////////////////////////////////

public class TransactionPageController {
    public Transaction__c trans{get;set;}
    public List<Product_Line__c> productLines{get;set;}
    Id currentUser = UserInfo.getUserId();
    CurrentTransaction currentTrans = new CurrentTransaction();
    public List<String> TotalCost {get;set;}
    public string GrandTotal {get;set;}
    
    public TransactionPageController(){
        //currentTrans will query take the current user and get the active transaction assciated with that user
        trans = currentTrans.Trans;
        //get the product lines with the current transaction as their parent
        productLines = [SELECT Name, Transaction__c, Product__c, Quantity__c, Total_Cost__c FROM Product_Line__c WHERE Transaction__c =: trans.id];
        //This for loop is to get the total cost as a string so we can display it
        TotalCost = new List<String>();
        for (Product_Line__c pl : productLines){
      		String tc = String.valueOf(pl.Total_Cost__c);
            TotalCost.add(tc);
        }
        //Also needed to so the grand total will display
		GrandTotal = String.valueOf(trans.Total_Cost__c);
    }
    

    public PageReference save(){
        trans.Status__c = 'Closed';
        //Creating a new transaction with the status of Active after closing the old one
        Transaction__c newTransaction = new Transaction__c(Contact__c = trans.Contact__c, Store_Location__c = trans.Store_Location__c, Salesperson__c = trans.Salesperson__c, Status__c = 'Active');
        update trans;
        insert newTransaction;
        //now setting our trans to the new one
        trans = newTransaction;
        //the rest of the code is needed to rerender the page on click with the updated info, so re-calling everything
        currentTrans.setCurrentTransaction(newTransaction);
        productLines = [SELECT Name, Transaction__c, Product__c, Quantity__c FROM Product_Line__c WHERE Transaction__c =: newTransaction.id];
        TotalCost = new List<String>();
        for (Product_Line__c pl : productLines){
      		String tc = String.valueOf(pl.Total_Cost__c);
            TotalCost.add(tc);
        }
        GrandTotal = String.valueOf(trans.Total_Cost__c);
        return Page.TransactionPage;
    }
    public PageReference updatePage(){
        //because of outputfield with inline support, just updates the database
        upsert productLines;
        //re-calling everything for the rerender so the info is correct
        currentTrans = new CurrentTransaction();
        trans = currentTrans.Trans;
        productLines = [SELECT Name, Transaction__c, Product__c, Quantity__c, Total_Cost__c FROM Product_Line__c WHERE Transaction__c =: trans.id];
        TotalCost = new List<String>();
        for (Product_Line__c pl : productLines){
      		String tc = String.valueOf(pl.Total_Cost__c);
            TotalCost.add(tc);
        }
        GrandTotal = String.valueOf(trans.Total_Cost__c);
        return Page.TransactionPage;
    }

    }