PartyPalace/force-app/main/default/objects/Product_Line__c/Product_Line__c.object-meta.xml
<CustomObject>
    <label>Store Product Line</label>
    <nameField>
        <displayFormat>PID-{0000}</displayFormat>
        <label>Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Store Product Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Store_Product__c</referenceTo>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Product_Line__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Store Product Lines</relationshipLabel>
    <relationshipName>Product_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ballons</fullName>
                <default>true</default>
                <label>Ballons</label>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Confetti</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Halloween</fullName>
            </value>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Christmas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/IsRented__c.field-meta.xml
<CustomField>
    <fullName>IsRented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rented?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ShoppingCartApexTest.cls
@isTest
public class ShoppingCartApexTest {
    @TestSetup static void tests(){
        Contact cont = new Contact(LastName='namerson');
        Insert cont;
        Id recID = Schema.SObjectType.Store_Product__c.getRecordTypeInfosByName().get('Rental').getRecordTypeId();
        
        List<Store_Product__c> testPros = new List<Store_Product__c>();
        for(Integer i = 0; i < 10; i++){
            testPros.add(new Store_Product__c(Name='Balloons'+i,Category__c='Confetti',IsRented__c = false,Price_Per_Unit__c=12.99,Rating__c=80, recordTypeId=recID));
   			
        }
        Insert testPros;
        
    }
    

    
    @isTest public static void savePurchaseTest(){
        List<Product_Line__c> testProdLine = new List<Product_Line__c>();
        List<Store_Product__c> testpros = [SELECT name, category__c, price_per_unit__c, rating__c, recordTypeID FROM Store_Product__c ];
        for(Store_Product__c item : testPros){
            testProdLine.add(new Product_Line__c(product__c=item.Id, quantity__c=2));
        }
        Contact cont = [SELECT id FROM Contact];
        shoppingCartApexController.savePurchase(testProdLine, cont.Id);
        transaction__c things = [SELECT id, contact__c FROM transaction__c];
        Product_Line__c[] prodsline = [SELECT id, quantity__c, product__c, transaction__c FROM Product_Line__c];
        system.assertEquals(things.contact__c, cont.Id);
        system.assertEquals(prodsline.size(), testProdLine.size() );
    }
}