force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>Delivery-{0000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Delivery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Delivery__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks to see if it has been delivered</description>
    <label>Delivered</label>
    <type>Checkbox</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Delivery__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Delivery__c/fields/Installer__c.field-meta.xml
<CustomField>
    <fullName>Installer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer</label>
    <referenceTo>Installer__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Rental_Period__c.field-meta.xml
<CustomField>
    <fullName>Rental_Period__c</fullName>
    <inlineHelpText>Please Select the length of the rental period</inlineHelpText>
    <label>Rental Period</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 Hour</fullName>
                <default>true</default>
                <label>24 Hour</label>
            </value>
            <value>
                <fullName>48 Hour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installer__c/Installer__c.object-meta.xml
<CustomObject>
    <label>Installer</label>
    <nameField>
        <label>Installer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <label>Rental Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental_Line__c/Rental_Line__c.object-meta.xml
<CustomObject>
    <label>Rental Line</label>
    <nameField>
        <displayFormat>RID-{0000}</displayFormat>
        <label>RentalID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Line__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Delivery in which the Rental Item is delivered</description>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Rental Lines</relationshipLabel>
    <relationshipName>Rental_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental_Line__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Rental Lines</relationshipLabel>
    <relationshipName>Rental_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Rental_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Rental Lines</relationshipLabel>
    <relationshipName>Rental_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Period__c/Rental_Period__c.object-meta.xml
<CustomObject>
    <label>Rental Period</label>
    <nameField>
        <displayFormat>Rental -{0000}</displayFormat>
        <label>Rental Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Rental_Period__c/fields/Installer__c.field-meta.xml
<CustomField>
    <fullName>Installer__c</fullName>
    <label>Installer</label>
    <referenceTo>Installer__c</referenceTo>
    <relationshipLabel>Rental Periods</relationshipLabel>
    <relationshipName>Rental_Periods</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Rental_Period__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Rental Periods</relationshipLabel>
    <relationshipName>Rental_Periods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/classes/DeliveryTriggerTest.cls
///////////////////////////////////////////////////////////////////////////
//
// Name: DeliveryTriggerTest
// Author: Andrew Sutton
// Created 4/10/2021
// Updated 4/14/2021
//
//
/////////////////////////////////////////////////////////////////////////////

@istest
public class DeliveryTriggerTest {
    @isTest static void singleTest(){
        Installer__c ins = new Installer__c(name = 'chad');
        insert ins;
        Rental__c rent = new Rental__c(name = 'house', Price_Per_Unit__c = 2);
        insert rent;
        Rental__c rent2 = new Rental__c(name = 'chair', Price_Per_Unit__c = 1);
        insert rent2;
        Transaction__c trans = new Transaction__c();
        insert trans;
        Contact contact = new Contact(LastName = 'test');
        insert contact;
        Date myDate = Date.newInstance(1960, 2, 17);
        Delivery__c del = new Delivery__c(Contact__c = contact.id, Installer__c = ins.id, Delivery_Date__c = myDate, Rental_Period__c = '24 Hour');
        insert del;
        Rental_Line__c rental1 = new Rental_Line__c(Transaction__c = trans.id, Rental__c = rent.id, Delivery__c = del.Id, Quantity__c = 1);
        insert rental1;
        Rental_Line__C rental2 = new Rental_Line__c(Transaction__c = trans.id, Rental__c = rent2.id, Delivery__c = del.Id, Quantity__c = 1);
        insert rental2;
        rental2.Quantity__c = 2;
        update rental2;
        del.Delivered__c = true;
        update del;

    }
}