force-app/main/default/objects/Delivery__c/Delivery__c.object-meta.xml
<CustomObject>
    <label>Delivery</label>
    <nameField>
        <displayFormat>Delivery-{0000}</displayFormat>
        <label>Delivery Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deliveries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Delivery__c/fields/Delivered__c.field-meta.xml
<CustomField>
    <fullName>Delivered__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checks to see if it has been delivered</description>
    <label>Delivered</label>
    <type>Checkbox</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Delivery__c/fields/Delivery_Date__c.field-meta.xml
<CustomField>
    <fullName>Delivery_Date__c</fullName>
    <label>Delivery Date</label>
    <type>Date</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Delivery__c/fields/Installer__c.field-meta.xml
<CustomField>
    <fullName>Installer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Installer</label>
    <referenceTo>Installer__c</referenceTo>
    <relationshipLabel>Deliveries</relationshipLabel>
    <relationshipName>Deliveries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Delivery__c/fields/Rental_Period__c.field-meta.xml
<CustomField>
    <fullName>Rental_Period__c</fullName>
    <inlineHelpText>Please Select the length of the rental period</inlineHelpText>
    <label>Rental Period</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24 Hour</fullName>
                <default>true</default>
                <label>24 Hour</label>
            </value>
            <value>
                <fullName>48 Hour</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Installer__c/Installer__c.object-meta.xml
<CustomObject>
    <label>Installer</label>
    <nameField>
        <label>Installer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Installers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <label>Rental Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Line__c/Rental_Line__c.object-meta.xml
<CustomObject>
    <label>Rental Line</label>
    <nameField>
        <displayFormat>RID-{0000}</displayFormat>
        <label>RentalID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Line__c/fields/Delivery__c.field-meta.xml
<CustomField>
    <fullName>Delivery__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Delivery in which the Rental Item is delivered</description>
    <label>Delivery</label>
    <referenceTo>Delivery__c</referenceTo>
    <relationshipLabel>Rental Lines</relationshipLabel>
    <relationshipName>Rental_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Rental_Line__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Rental Lines</relationshipLabel>
    <relationshipName>Rental_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Period__c/Rental_Period__c.object-meta.xml
<CustomObject>
    <label>Rental Period</label>
    <nameField>
        <displayFormat>Rental -{0000}</displayFormat>
        <label>Rental Period Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Periods</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Rental_Period__c/fields/Installer__c.field-meta.xml
<CustomField>
    <fullName>Installer__c</fullName>
    <label>Installer</label>
    <referenceTo>Installer__c</referenceTo>
    <relationshipLabel>Rental Periods</relationshipLabel>
    <relationshipName>Rental_Periods</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Rental_Period__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Rental Periods</relationshipLabel>
    <relationshipName>Rental_Periods</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/DeliveryTriggerHandler.cls
///////////////////////////////////////////////////////////////////////////
//
// Name: DelvieryTriggerHandler
// Author: Andrew Sutton
// Created 4/10/2021
// Updated 4/14/2021
//
//
/////////////////////////////////////////////////////////////////////////////

public class DeliveryTriggerHandler {
    public static void createDelivery(List<Delivery__c> Deliveries){
        For(Delivery__c d:Deliveries){
            checkForDelivery(d);
        }
        setRentalPeriod(Deliveries);
        
    }
    public static void updateDelivery(List<Delivery__c> DeliveriesNew, List<Delivery__c> DeliveriesOld){
        For(Delivery__c d:DeliveriesOld){
            checkForDelivery(d);
        }
        setRentalPeriod(DeliveriesNew);
    }
    public static void checkForDelivery(Delivery__c Delivery){
        if (Delivery.Delivered__c){
            Delivery.addError('Already Delivered, cannot make any changes');
        }
        
    }
    public static void setRentalPeriod(List<Delivery__c> Deliveries){
        set<id> instID = new set<id>();
        for(Delivery__c d:Deliveries){
            instID.add(d.Installer__c);
        }
        set<id> deliveryID = new set<id>();
        for(Delivery__c d: Deliveries){
            deliveryID.add(d.id);
        }
        List<Installer__c> installers = [SELECT name FROM Installer__c WHERE ID =: instID];
        List<Rental_Line__c> Rentals = [SELECT name, Rental__c FROM Rental_Line__c WHERE Delivery__c =: deliveryID];
        List<Rental_Period__c> newRentalPeriods = new List<Rental_Period__c>();
        For(Delivery__c d:Deliveries){
            if (d.Delivered__c){
                For(Rental_Line__c rentalLine : Rentals){
                    For(Installer__c ins: installers){
                        Rental_Period__c rentalPeriod = new Rental_Period__c(Rental__c = rentalLine.Rental__c, Installer__c = ins.Id);
                        rentalPeriod.Start_Date__c = d.Delivery_Date__c;
                        if(d.Delivery_Date__c == null){
                            d.Delivery_Date__c = date.today();
                        }
                        Switch on d.Rental_Period__c{
                            when '24 Hour'{
                                rentalPeriod.End_Date__c = d.Delivery_Date__c + 1;
                            }
                            when '48 Hour'{
                                rentalPeriod.End_Date__c = d.Delivery_Date__c + 2;
                            }
                        }
                        newRentalPeriods.add(rentalPeriod);
                    }
                }
            }
        }
        if(!newRentalPeriods.isEmpty()){
        	Insert newRentalPeriods;
        }
    }
}