PartyPalace/force-app/main/default/objects/Rental__c/Rental__c.object-meta.xml
<CustomObject>
    <label>Rental</label>
    <nameField>
        <label>Rental Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rentals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Rental_Inventory__c/Rental_Inventory__c.object-meta.xml
<CustomObject>
    <label>Rental Inventory</label>
    <nameField>
        <label>Rental Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rental Inventories</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Inventory__c/fields/Quantity_In_Stock__c.field-meta.xml
<CustomField>
    <fullName>Quantity_In_Stock__c</fullName>
    <label>Quantity In Stock</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Rental_Inventory__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Rental Inventories</relationshipLabel>
    <relationshipName>Rental_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Rental_Inventory__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Rental Inventories</relationshipLabel>
    <relationshipName>Rental_Inventories</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Rental_Line__c/Rental_Line__c.object-meta.xml
<CustomObject>
    <label>Rental Line</label>
    <nameField>
        <displayFormat>RID-{0000}</displayFormat>
        <label>RentalID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rental Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Rental_Line__c/fields/Rental__c.field-meta.xml
<CustomField>
    <fullName>Rental__c</fullName>
    <label>Rental</label>
    <referenceTo>Rental__c</referenceTo>
    <relationshipLabel>Rental Lines</relationshipLabel>
    <relationshipName>Rental_Lines</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Rental_Line__c/fields/Transaction__c.field-meta.xml
<CustomField>
    <fullName>Transaction__c</fullName>
    <label>Transaction</label>
    <referenceTo>Transaction__c</referenceTo>
    <relationshipLabel>Rental Lines</relationshipLabel>
    <relationshipName>Rental_Lines</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Transaction__c/Transaction__c.object-meta.xml
<CustomObject>
    <label>Transaction</label>
    <nameField>
        <displayFormat>TRN-{0000}</displayFormat>
        <label>Transaction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

PartyPalace/force-app/main/default/objects/Transaction__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Rental_Cost__c +  Products_Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Cost</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Transaction__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Warehouse</label>
    <referenceTo>Warehouse__c</referenceTo>
    <relationshipLabel>Transactions</relationshipLabel>
    <relationshipName>Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Warehouse__c/Warehouse__c.object-meta.xml
<CustomObject>
    <label>Warehouse</label>
    <nameField>
        <label>Warehouse Locations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Warehouses</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/RentalLineTriggerHandler.cls
///////////////////////////////////////////////////////////////////////////
//
// Name: RentalLineTriggerHandler
// Author: Andrew Sutton
// Created 4/10/2021
// Updated 4/12/2021
//
//
/////////////////////////////////////////////////////////////////////////////


public class RentalLineTriggerHandler {
    public static void executeInsert(List<Rental_Line__c> newRentals){
        updateInventory(newRentals);
        updateTotalCost(newRentals);
        
    }
    
    public static void updateTotalCost(List<Rental_Line__c> newRentals)
    {
        List<Rental__c> Rentals = [SELECT Price_Per_Unit__c FROM Rental__c];
        for (Rental_Line__c rl: newRentals){
            for(Rental__c r: Rentals){
                if(rl.Rental__c == r.id){
                    rl.Total_Cost__c = r.Price_Per_Unit__c * rl.Quantity__c;
                }
                
            }
        }        
    }
    public static void updateInventory(List<Rental_Line__c> RentalLine){
        List<Rental_Inventory__c> inventories = findInventory(RentalLine);
        For(Rental_Line__c rl: RentalLine){
            For(Rental_Inventory__c inventory:inventories){
                //subtract From Inventory
                inventory.Quantity_in_Stock__c = inventory.Quantity_in_Stock__c - rl.Quantity__c;
                //Ask if we are out of stock
                if (inventory.Quantity_in_Stock__c < 0){
                    rl.Quantity__c.addError('Not enough in Stock');
                }
            }
        }
        update inventories;
    }
    static List<Rental_Inventory__c> findInventory(List<Rental_Line__c> RentalLines)
    {
        Set<id> transid = new set<id>();
        for(Rental_Line__c rl :RentalLines){
            transid.add(rl.Transaction__c);
        }
        Set<id> rentalId = new set<id>();
        for(Rental_Line__c rl : RentalLines){
            rentalID.add(rl.rental__c);
        }
        //Grab the transactions that matches our Rental Line item's transactions
        List<Transaction__c> trans = [SELECT Warehouse__c FROM Transaction__c WHERE id = : TransID];
        set<id> locationID = new set<id>();
        for(Transaction__c tran : trans){
            locationID.add(tran.Warehouse__c);
        }
        List<Rental_Inventory__c> inventory = [SELECT Quantity_in_Stock__c, Rental__c FROM Rental_Inventory__c WHERE Rental__c IN :rentalID AND Warehouse__c =: locationID];
        return inventory;
    }    
    
    
    
}