force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ballons</fullName>
                <default>true</default>
                <label>Ballons</label>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Confetti</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Halloween</fullName>
            </value>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Christmas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Star_Rating__c.field-meta.xml
<CustomField>
    <fullName>Star_Rating__c</fullName>
    <description>The average rating, use for star rating.</description>
    <formula>FLOOR( Rating__c / 20 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Star Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/TopListControllerTest.cls
@isTest
public class TopListControllerTest {
	
    @testSetup
    public static void setupTest() {
        List<Store_Product__c> pList = new List<Store_Product__c>();
        for (Integer i = 0; i < 150; i++) {
            Store_Product__c newProduct = new Store_Product__c();
            newProduct.Category__c = 'Banners';
            newProduct.Rating__c = Math.mod(i, 100);
            pList.add(newProduct);
        }
        Insert pList;
    }
    
    @isTest
    public static void TP_GetProducts() {
        List<Store_Product__c> expectedResults = [SELECT id FROM Store_Product__c ORDER BY Star_Rating__c DESC LIMIT 10];
        List<Store_Product__c> actualResults = TopListController.GetProducts();
        
        System.assertEquals(10, actualResults.size());
        for(Integer i = 0; i < actualResults.size(); i++) {
            System.assertEquals(expectedResults.get(i).id, actualResults.get(i).id);
        }
    }
}