force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ballons</fullName>
                <default>true</default>
                <label>Ballons</label>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Confetti</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Halloween</fullName>
            </value>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Christmas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/IsRented__c.field-meta.xml
<CustomField>
    <fullName>IsRented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rented?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

force-app/main/default/classes/SearchCategoryControllerTest.cls
@isTest
public class SearchCategoryControllerTest {
    @isTest(SeeAllData=false)
    static void TestSearchCategoryController(){
        // Test data setup
        List<Store_Product__c> testPros = new List<Store_Product__c>();
        for(Integer i = 0; i < 10; i++){
            testPros.add(new Store_Product__c(Name='Balloons'+i,Category__c='Confetti',IsRented__c = false,Price_Per_Unit__c=12.99,Rating__c=80));
        }
        for(Integer i = 0; i < 10; i++){
            testPros.add(new Store_Product__c(Name='Balloons'+i,Category__c='Halloween',IsRented__c = false,Price_Per_Unit__c=12.99,Rating__c=80));
        }
        
        // insert test data
        insert testPros;
        
        // Setting parameters for method 
        Test.startTest();
        Integer pageSize = 100;
        Integer pageNumber = 1;
        Integer price = 300;
        String rating = '5';
        String searchKeyword = null;
        String [] cbFilter = new String []{'Confetti','Birthday'};
        Boolean rental = false;
        
        // declare return list results
        List <Store_Product__c> myPro = new List <Store_Product__c>();
        
        // With checkbox filter 
        myPro = SearchCategoryController.getPro(pageSize, pageNumber, price, rating, searchKeyword, cbFilter, rental);
        System.debug(myPro);
        System.debug(myPro.size());
        System.assertEquals(10,myPro.size());
        
        // Without checkbox filter 
        cbFilter = new List<String>();
        myPro = SearchCategoryController.getPro(pageSize, pageNumber, price, rating, searchKeyword, cbFilter, rental);
        Test.stopTest();
        System.debug(myPro);
        System.debug(myPro.size());
        System.assertEquals(20,myPro.size());
    }
}