force-app/main/default/objects/Store_Product__c/Store_Product__c.object-meta.xml
<CustomObject>
    <label>Store Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Store Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Store_Product__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ballons</fullName>
                <default>true</default>
                <label>Ballons</label>
            </value>
            <value>
                <fullName>Banners</fullName>
            </value>
            <value>
                <fullName>Confetti</fullName>
            </value>
            <value>
                <fullName>Graduation</fullName>
            </value>
            <value>
                <fullName>Halloween</fullName>
            </value>
            <value>
                <fullName>Birthday</fullName>
            </value>
            <value>
                <fullName>Wedding</fullName>
            </value>
            <value>
                <fullName>Christmas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/IsRented__c.field-meta.xml
<CustomField>
    <fullName>IsRented__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rented?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Price_Per_Unit__c.field-meta.xml
<CustomField>
    <fullName>Price_Per_Unit__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

PartyPalace/force-app/main/default/objects/Store_Product__c/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <label>Product Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Rental_End__c.field-meta.xml
<CustomField>
    <fullName>Rental_End__c</fullName>
    <label>Rental End</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Rental_Start__c.field-meta.xml
<CustomField>
    <fullName>Rental_Start__c</fullName>
    <label>Rental Start</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/fields/Star_Rating__c.field-meta.xml
<CustomField>
    <fullName>Star_Rating__c</fullName>
    <description>The average rating, use for star rating.</description>
    <formula>FLOOR( Rating__c / 20 )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Star Rating</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Store_Product__c/recordTypes/Rental.recordType-meta.xml
<RecordType>
    <fullName>Rental</fullName>
    <active>true</active>
    <label>Rental</label>
</RecordType>

force-app/main/default/classes/SearchCategoryController.cls
public class SearchCategoryController {
    @AuraEnabled
    public static List <Store_Product__c> getPro(Integer pageSize, Integer pageNumber,Integer price,
                                                 String rating,String searchKeyword,String [] cbFilter, Boolean rental) {
        
        System.debug(rental);                                             
        //convert rating
        Integer ratingInt = 5;
       	If(!String.isBlank(rating)){
            ratingInt=integer.valueOf(rating);
        }
       	ratingInt = (ratingInt*20);
                                                     
                                                     
        //convert offset                                             
        Integer offset = (pageNumber - 1) * pageSize;
		
        //if search key is blank then show everything if not blank search with wildcard                                              
 		String searchkey= String.isBlank (searchKeyWord) ? '%%' : '%'+searchKeyword+'%';
        
        //declare product list                                             
        List<Store_Product__c> pros = new List <Store_Product__c>();                                           
                                                     
        if(cbFilter.isEmpty()){
			 pros = [SELECT Id, Name, Category__c, Rating__c, Price_Per_Unit__c, Star_Rating__c, Product_Description__c,
                                            Rental_Start__c, Rental_End__c
                    FROM Store_Product__c
                    WHERE Name LIKE : searchkey
                    AND   IsRented__c =:  rental 
                    AND	  Price_Per_Unit__c <= : price
                    AND	  rating__c <= : ratingInt                        
                   		  LIMIT :pageSize OFFSET :offset
                          ];  
        }else{
            pros = [SELECT Id, Name, Category__c, Rating__c, Price_Per_Unit__c, Star_Rating__c, Product_Description__c,
                                            Rental_Start__c, Rental_End__c 
                    FROM Store_Product__c
                    WHERE Name LIKE : searchkey
                    AND   IsRented__c =:  rental 
                    AND   Category__c IN:cbFilter
                    AND   Price_Per_Unit__c <= : price
                    AND	  rating__c <= : ratingInt
                          LIMIT :pageSize OFFSET :offset
                          ];            
        }
           
 	return pros;
    }
    
}